### ISSUE TITLE
Misalignment of right single spectrum view with main spectrogram

### ISSUE THREAD

**Issue by liam-clink** [Christoph-Lauer/Sonogram#4]
![Screenshot (154)_LI](https://user-images.githubusercontent.com/59755195/144699139-775b418b-ec90-4a71-b9c1-626bc1a2b777.jpg)
The main spectrograph appears to be binned incorrectly in the frequency (vertical) axis when window size is set to 8192k, and the single spectrum on the right appears to be hiding behind another part of the window. I have marked both of these problems in the attached image.

**Comment by Christoph-Lauer** [comment]
You are correct, perhaps I find time to fix it...

**Comment by Christoph-Lauer** [comment]
Fixed this bug.

**Comment by Christoph-Lauer** [comment]
I close this issue

**Comment by Christoph-Lauer** [comment]
I fexed this bug!
